services:
  mqtt-broker:
    image: emqx/emqx:5.8.5
    container_name: pizza-mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    environment:
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "public"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log

  ms1:
    build:
      context: ./MS1
    container_name: pizza-ms1
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    environment:
      PORT: "8080"
      MQTT_BROKER_URL: mqtt://mqtt-broker:1883
      MQTT_TOPIC_PREFIX: pizza-service/events
      MQTT_STATUS_TOPIC: pizza-service/status/ms1
      MQTT_QOS: "1"
      DB_FILE: /data/pizza-service.db
    ports:
      - "8080:8080"
    volumes:
      - ms1_db_data:/data

  ms2:
    build:
      context: ./MS2
    container_name: pizza-ms2
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    environment:
      MQTT_BROKER_URL: mqtt://mqtt-broker:1883
      MQTT_TOPIC: pizza-service/events/#
      MQTT_QOS: "1"

volumes:
  ms1_db_data:
  emqx_data:
  emqx_log:
